# _config.yml
title: UTCDW Guidebook
author: Mike Morris, Karen Smith, and Paul Kushner
logo: logo.png
exclude_patterns: [.DS_Store, "**.ipynb_checkpoints", "paper*"]
only_build_toc_files: true
execute:
    execute_notebooks: cache

    timeout: 1200

latex:
    latex_engine: pdflatex
    use_jupyter_latex: true

repository:
    url: https://github.com/mikemorris12/UTCDW_Guidebook

html:
  use_respository_button: true
  extra_footer: |
    <p>
    &copy; 2024 -- This work is licensed under Creative Commons Attribution Share Alike 4.0 International (CC-BY-SA) <br>
    </p>

bibtex_bibfiles:
    - guidebook_references.bib

sphinx:
  config:
    bibtex_reference_style: author_year
